[build]
  # 不构建，直接使用deploy-package
  command = ""
  publish = "deploy-package"
  functions = "deploy-package/netlify/functions"

# 重定向配置
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
