[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/users"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  from = "/api/users/search"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  from = "/api/users/:id/transfer-role"
  to = "/.netlify/functions/transfer-role"
  status = 200

[[redirects]]
  from = "/api/setup-founder"
  to = "/.netlify/functions/setup-founder"
  status = 200

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/api/pending-content"
  to = "/.netlify/functions/pending-content"
  status = 200

[[redirects]]
  from = "/api/pending-content/:id/review"
  to = "/.netlify/functions/test-review"
  status = 200

[[redirects]]
  from = "/api/pending-content/:id"
  to = "/.netlify/functions/update-content"
  status = 200

[[redirects]]
  from = "/api/me"
  to = "/.netlify/functions/user-profile"
  status = 200

[[redirects]]
  from = "/api/user-profile-complete"
  to = "/.netlify/functions/user-profile"
  status = 200

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/feedback"
  to = "/.netlify/functions/feedback"
  status = 200

[[redirects]]
  from = "/api/crosscampus"
  to = "/.netlify/functions/crosscampus"
  status = 200

[[redirects]]
  from = "/api/activity"
  to = "/.netlify/functions/activity"
  status = 200

[[redirects]]
  from = "/api/art"
  to = "/.netlify/functions/art"
  status = 200

[[redirects]]
  from = "/api/art/:id/like"
  to = "/.netlify/functions/art"
  status = 200

[[redirects]]
  from = "/api/study"
  to = "/.netlify/functions/study"
  status = 200

[[redirects]]
  from = "/api/user-content-status"
  to = "/.netlify/functions/user-content-status"
  status = 200

[[redirects]]
  from = "/api/env-check"
  to = "/.netlify/functions/env-check"
  status = 200

[[redirects]]
  from = "/api/debug"
  to = "/.netlify/functions/debug"
  status = 200

[[redirects]]
  from = "/api/test-basic"
  to = "/.netlify/functions/test-basic"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
